# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/03_utils.plot.ipynb.

# %% auto 0
__all__ = ['fig', 'func_show', 'figsz']

# %% ../../nbs/03_utils.plot.ipynb 3
from fastai.basics import *
from fastai.test_utils import *

# %% ../../nbs/03_utils.plot.ipynb 4
def func_show(f: callable, ax: plt.Axes=None, bounds: tuple[float]=(-2,2), title: str=""):
    "Draw 1d function `f`."
    if ax is None: ax = plt.subplots(figsize=(3,2))[1]
    xs = np.linspace(*bounds, 100)
    ax.plot(xs, f(xs))
    ax.set_xlabel('x');ax.set_ylabel('y');ax.set_title(title)

# %% ../../nbs/03_utils.plot.ipynb 6
fig = plt.gcf(); _default_dpi = fig.dpi; plt.close(fig)

def figsz(sz: tuple[float], unit: str="cm") -> tuple[float]:
    "Converts the `sz` (width, height) in `unit` to inches."
    _cm = 1/2.54; _pixel = 1/_default_dpi
    w,h = sz
    if unit == "cm": return (w*_cm, h*_cm)
    elif unit == "pixel": return (w*_pixel, h*_pixel)
    else: raise ValueError(f'unit {unit} is invalid.')
