project:
  type: website

format:
  html:
    theme:
      light: [cosmo, theme-custom.scss]
      dark: [darkly, theme-custom.scss]
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  reader-mode: true
  navbar:
    background: primary
    search: true
  sidebar:
    style: floating

metadata-files: [nbdev.yml, sidebar.yml]